"""add ttft_ms to request_logs

Revision ID: d0caa44f82d4
Revises: e3627e58eb08
Create Date: 2026-10-08 11:21:44.569234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0caa44f82d4'
down_revision: Union[str, None] = 'e3627e58eb08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_logs', sa.Column('ttft_ms', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_logs', 'ttft_ms')
    # ### end Alembic commands ###
